### ISSUE TITLE
BlinkID v5.10.0 SPM Issue

### ISSUE THREAD

**Issue by DomiTillman** [BlinkID/blinkid-ios#341]
Hi guys, I'm experiencing an issue with SPM as of v5.10. 
### Describe your environment

  - Xcode version: 12.5
  - BlinkID SDK version: 5.10.0
  - What are you trying to scan: 

### Describe the problem

Swift Package Manager fails to install 5.10.0 with the below error:

### Relevant code

```swift
checksum of downloaded artifact of binary target 'Microblink' (7f7f9a509783f70ceb8e1b3fe8350589af7a087a10093a2047ce9154db4a2685) does not match checksum specified by the manifest (b8e902bc45fcb7df97eba3e50e129b28f47b9316f63ae6fe614621455d8c8a1d)
```
v5.9.0 still installs fine, if that helps.

**Comment by juraskrlec** [comment]
Hi @DomiTillman,

This should be resolved now, please try it out :)

**Comment by DomiTillman** [comment]
> Hi @DomiTillman,
> 
> This should be resolved now, please try it out :)

Thanks for the prompt response! 

I'm getting a different error for that version now - 
```
"blinkid-swift-package" could not be resolved 

```
I've also tried resetting local caches as well.

**Comment by juraskrlec** [comment]
Can you please share more details, did you try to remove derived data and clean everything? I've tried several times on our Sample project, and everything is resolved properly, I can't get this error?

**Comment by DomiTillman** [comment]
I cleared the derived data this morning as was able to get it resolved. Thank you!

**Comment by DomiTillman** [comment]
Oops, I think I spoke too soon. I rebuilt this once again and found the above issue reappearing. It appears as though the Package.swift file isn't updating the checksum when the framework gets exported (or something like that?).

**Comment by mikeberlin** [comment]
@juraskrlec any update on this? this is still an issue with version 5.11.0

**Comment by mijo-gracanin** [comment]
@mikeberlin, I just updated the package. Please let me know if it works for you now. Thanks!

**Comment by mikeberlin** [comment]
I'm now able to compile. Thanks!
